name: Fetch Kroger Egg Prices - First Half
on:
  schedule:
    - cron: '0 7 * * *' # Runs daily at midnight PDT (7 AM UTC)
  workflow_dispatch:
jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      START_AT: '0'
      END_AT: '1500'
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      KROGER_CLIENT_ID: ${{ secrets.KROGER_CLIENT_ID }}
      KROGER_CLIENT_SECRET: ${{ secrets.KROGER_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Fetch Kroger Egg Prices (first half)
        run: node scripts/fetch-kroger-egg-prices.js 